baseURL = 'http://lovelinyj.github.io/'
languageCode = 'en-us'
title = "Musky's blog"
theme = "anatole"

[params]
title = "I'm Musky"
author = "Musky"
description = "Call me Musky"
profilePicture = "images/profile.jpg"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:musky@gmail.com"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"